### ISSUE TITLE
TraDeS for Instance Segmentation

### ISSUE THREAD

**Issue by nguyenpbui** [JialianW/TraDeS#34]
Thank you for your awesome research work.
I have a question related to segmentation task by this repo. I followed your instructions to run validation on YoutubeVIS 2019, but the results is in tracking format. Does this repo support segmentation format?
Thank you.

**Comment by JialianW** [comment]
Sorry, we didn't do this. You may transfer by yourself.

**Comment by Kunaldargan** [comment]
How to evaluate ytvis to achieve AP as quoted in the paper. I have custom trained using ytvis format need to find AP.

Thanks

**Comment by JialianW** [comment]
> How to evaluate ytvis to achieve AP as quoted in the paper. I have custom trained using ytvis format need to find AP.
> 
> Thanks

We evaluate on the Youtube-VIS official evaluation server. Not sure if there is an available AP evaluation code.

**Comment by Kunaldargan** [comment]
In order to evaluate on Youtube-VIS evaluation server, you had converted the tracking format to ytvis/coco format ? Evaluation code is given in MaskTrackRCNN repository  MaskTrackRCNN/mmdet/core/evaluation/coco_utils.py it calls pycocotools.ytvoseval

from pycocotools.ytvoseval import YTVOSeval

from .recall import eval_recalls


def ytvos_eval(result_file, result_types, ytvos, max_dets=(100, 300, 1000)):

    if mmcv.is_str(ytvos):
        ytvos = YTVOS(ytvos)
    assert isinstance(ytvos, YTVOS)

    if len(ytvos.anns) == 0:
        print("Annotations does not exist")
        return
    assert result_file.endswith('.json')
    ytvos_dets = ytvos.loadRes(result_file)

    vid_ids = ytvos.getVidIds()
    for res_type in result_types:
        iou_type = res_type
        ytvosEval = YTVOSeval(ytvos, ytvos_dets, iou_type)
        ytvosEval.params.vidIds = vid_ids
        if res_type == 'proposal':
            ytvosEval.params.useCats = 0
            ytvosEval.params.maxDets = list(max_dets)
        ytvosEval.evaluate()
        ytvosEval.accumulate()
        ytvosEval.summarize()

This can be added as a seperate evaluation in this repository also, input is ytvis format output.json

**Comment by Kunaldargan** [comment]
ytvis format assumes one object per frame ?

**Comment by lpwMei** [comment]
Have you achieved it? I have the same problem.
