### ISSUE TITLE
Question about the code for CVA Tracking Offset Step 2

### ISSUE THREAD

**Issue by HYUNJS** [JialianW/TraDeS#7]
Hi :) Thank you for sharing this wonderful work! I am really interested in your work.

According to the equation 2) in your paper (arxiv version), s is the feature stride of e' (= 8). However, when I read the code, it seems that s=2 is used instead of 8. Although I don't think using s=2 makes much difference in the model performance, I would like to check with you which value is the correct one to use.

Corresponding code is here.
https://github.com/JialianW/TraDeS/blob/master/src/lib/model/networks/base_model.py#L77

```
self.m = np.reshape(off_template_w, newshape=(h * w, w))[None, :, :] * 2
self.v = np.reshape(off_template_h, newshape=(h * w, h))[None, :, :] * 2
```

**Comment by JialianW** [comment]
Thanks for your interest and question!

The tracking offset from CVA is used for two purposes: 1. feature propagation in MFW; 2. data association. 

1. For feature propagation in MFW, since it is based on the feature map (which has been downsampled), we only need to multiply a factor of 2 to indicate the object offsets on the feature map. 

2. For data association, it operates in the post-processing stage where the detection boxes have been rescaled to the original image size, we therefore need to multiply a factor of 8. This multiplication should be in this place (https://github.com/JialianW/TraDeS/blob/964258e8d436e9994472e5fb788695ed8fb60357/src/lib/utils/post_process.py#L48).

In the paper, including O^C, equations 2&3, they are describing the object tracking offset in the original image size, which is slightly different from what we used for the MFW feature propagation as you had seen in 'base_model.py' (the former one needs a multiplication factor of 8 while the latter one just needs a factor of 2). In order to make the paper readily understandable, we have not clarified this yet. Again, thank you for proposing this question. Feel free to propose follow-up comments if you are still confused.
